version: 2.1
jobs:
  node:
    working_directory: ~/react-native-radar
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}
      - run: npm install
      - save_cache:
          name: Save node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: Test
          command: |
            mkdir -p test-results/jest
            npm run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - persist_to_workspace:
          root: ~/react-native-radar
          paths:
            - node_modules
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  android:
    working_directory: ~/react-native-radar/example
    docker:
      - image: circleci/android:api-28-node
    steps:
      - checkout:
          path: ~/react-native-radar
      - restore_cache:
          name: Restore node modules cache
          key: lock-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - run: sudo yarn install
      - run: sudo npm install -g react-native
      - save_cache:
          name: Save node modules cache
          key: lock-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - node_modules
      - run: cd android && ./gradlew assembleDebug
  ios:
    macos:
      xcode: "11.2.1"
    working_directory: ~/react-native-radar/example
    steps:
      - checkout:
          path: ~/react-native-radar
      - restore_cache:
          name: Restore node modules cache
          key: lock-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - run: sudo yarn install
      - run: sudo npm install -g react-native
      - save_cache:
          name: Save node modules cache
          key: lock-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - node_modules
      - run: cd ios && pod install
      - run: react-native run-ios
workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
