version: 2
jobs:
  test:
    working_directory: ~/react-native-radar
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}
      - run: npm install
      - save_cache:
          name: Save node modules cache
          key: lock-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: Test
          command: |
            mkdir -p test-results/jest
            npm run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - persist_to_workspace:
          root: ~/react-native-radar
          paths:
            - node_modules
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  version: 2
  node-android-ios:
    jobs:
      - test
